### ISSUE TITLE
Random crash I found

### ISSUE THREAD

**Issue by ShiroSeby** [tf2cheater2013/Fedoraware#172] opened 2022-04-10 00:09 UTC
**Fedoraware Version Date: #170 **  

## Config used:
Default Fedoraware config

## Description:  
It crashes your game when you do the steps below

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Load Fedoraware so you get the default config
2. Save the config with any name
3. Load the config
4. Change menu accent color then resize the menu
5. Save the config

## Additional context 

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by lnx00** [comment] 2022-04-10 00:26
I wasn't able to reproduce this issue:
https://streamable.com/8blgy0

**Comment by ShiroSeby** [comment] 2022-04-10 00:49
> I wasn't able to reproduce this issue: https://streamable.com/8blgy0

I did it on the tf2 menu, not in-game

**Comment by xxmyn** [comment] 2022-04-10 02:43
Maybe it's you? I can't reproduce this issue in the menu either.

**Comment by ShiroSeby** [comment] 2022-04-10 02:54
Well that's abnormal since I was able to crash the game several times with these steps, and yeah maybe it's just me

**Comment by johnathon-walnut** [comment] 2022-04-10 02:55
Atcnm a swbufwe then..

**Comment by johnathon-walnut** [comment] 2022-04-10 02:55
Attach a debugfe ghen

**Comment by johnathon-walnut** [comment] 2022-04-10 02:56
Debussy

**Comment by johnathon-walnut** [comment] 2022-04-10 02:56
Debugger

**Comment by ShiroSeby** [comment] 2022-04-10 02:57
Will try after I'm done with school assignments

**Comment by johnathon-walnut** [comment] 2022-04-10 02:57
Ok sir my friend get good gradings yes sir

**Comment by ShiroSeby** [comment] 2022-04-10 07:09
Tried using debugger, it didn't crash but when I use the release version it does crash. Weird

**Comment by xxmyn** [comment] 2022-04-11 05:52
I forgor to close this.

Can't reproduce, bye.

**Closed by xxmyn** 2022-04-11 05:52 UTC
