### ISSUE TITLE
Crash after Melee use

### ISSUE THREAD

**Issue by fakenotreaI** [tf2cheater2013/Fedoraware#474] opened 2022-07-01 01:18 UTC
Fedoraware Version Date: Thursday, ‎June ‎30, ‎2022, ‏‎3:42:38 PM
## Config used: 
https://files.catbox.moe/iwiv1t.fw
## Description:  
Whenever you use melee with the cheat, the game will crash after using it. This happens very often and needs to be fixed.

## Steps to reproduce:  

1. Go into a casual match
2. Take out your melee
3. Kill someone/people with it
4. Crash

Video recording:
https://youtu.be/EWTp2Db3-yk

**Comment by tf2cheater2013** [comment] 2022-07-01 05:00
could be a duplicate of #398 please check :D

**Comment by xxmyn** [comment] 2022-07-01 06:30
after seeing [this](https://youtu.be/EWTp2Db3-yk) I am sure it is a duplicate of issue #398

**Closed by xxmyn** 2022-07-01 06:30 UTC
